### ISSUE TITLE
[new protocol] Support for out-of-process panel widget menus

### ISSUE THREAD

**Issue by DemiMarie** [misyltoad/frog-protocols#11]
For user experience reasons, Qubes OS needs to implement custom menus and/or panel applications that are opened by clicking on a panel icon.  For maintainability reasons, these need to be implemented in a desktop-environment-independent way, though the launcher (the icon itself) can be per-desktop-environment.

Initially I thought that Qubes OS was the only project to need this, but it turns out that some other projects have similar or even stricter requirements.  Notably, some programs need to support e.g. volume sliders in their tray icon dropdowns.  The `com.canonical.dbusmenu` interface cannot express this, and current notification APIs are far from providing a suitable substitute.  These programs require an API that is completely independent of the desktop environment.

**Comment by Conan-Kudo** [comment]
This is not workable unless you can get desktops to implement such a protocol. So far, I don't think anyone is interested in such a thing.

**Comment by DemiMarie** [comment]
For Jay there is https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/355, and at least one KDE developer has also expressed interest in this.

**Comment by mahkoh** [comment]
I see no need for another protocol since I've already published https://github.com/mahkoh/jay-protocols/blob/master/unstable/jay-tray-v1.xml
