### ISSUE TITLE
Requesting to Enumerate Current Supported Compositors on Readme

### ISSUE THREAD

**Issue by TheCowboyHermit** [misyltoad/frog-protocols#5]
I am working/maintaining a GUI project project (alternative to QT and GTK, and it uses Vulkan API), and so I was curious to experiment some of the features coming up from this Frog Protocol. 

It would be useful to also provide information on which compositor currently offer support for Frog Protocol or which Pull Request to try.

For an example, in your other post on Gitlab, you provided this link to KWin's draft pull request that we can try on our end to test:

https://invent.kde.org/plasma/kwin/-/merge_requests/6474

It would be a good idea to add it to Readme along with any other compositors/versions that supports the Frog Protocol for testing/experimenting.

**Comment by serebit** [comment]
I think you misunderstand—there isn't anything called the "frog protocol". This repository serves as a collection of protocols just as [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols) does. If you want a support matrix for the protocols that this repository contains, I would suggest filing an issue on [wayland-explorer](https://github.com/vially/wayland-explorer), which serves as the current de facto protocol support matrix.

**Comment by vaxerski** [comment]
I've made an issue report over at wayland-explorer to add frog-* yesterday: https://github.com/vially/wayland-explorer/issues/92

when that gets done, you should be able to find that out on https://wayland.app, just like you can with other protocols.

**Comment by TheCowboyHermit** [comment]
Thank you for the clarification on that and honestly, everything related to Wayland have been a bit confusing. Still, I am excited about the prospect of porting my GUI Toolkit over to Wayland from X11.

**Comment by Vaisakhkm2625** [comment]
So just for clarity, is there a official place to discuss about a new protocol?? 

it was a nightmare to emulate  keyboard & mouse/touchpad/other input devices in wayland, in theory, we can always create fake devices and interfacing with uinput ,   but there are a lot of issues with that (like suppressing keyboard input for remapping...).  i really wanted to experiment with such things, or atleast discuss how to fix such things with devs that maintain such libs

**Comment by vaxerski** [comment]
New protocol discussions are done in MRs. You draft one, make a MR, and people will review it, ask questions, suggest improvements, give feedback.

The "official" place would be wayland-protocols on the freedesktop gitlab, for frog, that'd be this repo.

For emulating input devices, wlr extensions exist for this, but IIRC for other desktops your only bet is the RemoteDesktop portal: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.RemoteDesktop.html
Worth noting that should work on gnome and kde, but IIRC no other environment supports that. We have an open issue at hyprland's xdp, and IIRC someone is working on it, but for now we don't support it either

**Comment by Vaisakhkm2625** [comment]
> New protocol discussions are done in MRs. You draft one, make a MR, and people will review it, ask questions, suggest improvements, give feedback.
> 
> The "official" place would be wayland-protocols on the freedesktop gitlab, for frog, that'd be this repo.
> 
> For emulating input devices, wlr extensions exist for this, but IIRC for other desktops your only bet is the RemoteDesktop portal: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.RemoteDesktop.html Worth noting that should work on gnome and kde, but IIRC no other environment supports that. We have an open issue at hyprland's xdp, and IIRC someone is working on it, but for now we don't support it either

Thanks for the detailed response(and taking time to respond to me).. btw I can't thank enough for the work you do on hyprland... 

I will checkout remotedesktop protocol... i didn't thought we can use that for emulating devices too, i thoguht its only used for KDE connect and VNC...  hope remotedesktop protocol gets added soon enough in hyprland... things KDE Connect remote feature is something really wanted to use.. (🤔 now i wonder how  wayvnc works in hyprland... i have to look into it...) 
EDIT: got it, it creates virtual devices with wlr virtual keyboard and pointer protocol....  hope frog helps make those standard across gnome and kde...
